services:
  db:
    image: postgres:16
    container_name: ai_resume_db
    restart: always
    environment:
      POSTGRES_DB: ai_resume
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
    ports:
        - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ai_resume_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
